---
zookeeper_version: 3.4.9
zookeeper_user: zookeeper
zookeeper_group: zookeeper
zookeeper_conf_dir: /etc/zookeeper/conf
zookeeper_log_dir: /var/log/zookeeper
zookeeper_data_dir: /var/lib/zookeeper
zookeeper_maxClientCnxns: 50
zookeeper_client_port: 2181
apache_mirror: http://apache.cs.utah.edu/zookeeper/
