---
- name: Install nodejs
  become: yes
  become_user: root
  yum: name=nodejs state=present update_cache=yes enablerepo=epel
- name: Install npm
  become: yes
  become_user: root
  yum: name=npm state=present update_cache=yes enablerepo=epel
- name: Symlink nodejs to node
  become: yes
  become_user: root
  shell: ln -s "$(which nodejs)" {{node_path}} creates={{node_path}}
