---
- name: Install nodejs
  become: yes
  become_method: sudo
  apt: name=nodejs state=present
- name: Install npm
  become: yes
  become_method: sudo
  apt: name=npm state=present
- name: Symlink nodejs to node
  become: yes
  become_method: sudo
  shell: ln -s "$(which nodejs)" {{node_path}} creates={{node_path}}
