- name: Configure Zookeeper
  hosts: zookeeper
  become: yes
  become_user: ec2-user
  gather_facts: True
  roles:
    - zookeeper
  environment:
      BROKER_SOCKET: '{{ broker_ip }}:{{ broker_port }}'