---
- name: Create AWS instance
  hosts: localhost
  connection: local
  gather_facts: False
  remote_user: ubuntu
  roles:
    - { role: create_instances, group: zookeeper}

- name: Connection to zookeeper
  hosts: localhost

  tasks:
    - command: ansible-playbook connection.yml -i inventory 
