---
- hosts: bot
  roles:
      - bot

- hosts: producer
  roles:
      - producer
  environment:
      BROKER_SOCKET: '{{ broker_ip }}:{{ broker_port }}'
      ZOOKEEPER_SOCKET: '{{ zookeeper_ip }}:{{ zookeeper_port }}'
      DB_SOCKET: '{{ db_ip }}'
